import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {
  Box,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Typography,
} from "@mui/material";
import { useState, useEffect } from "react";
import PerfectScrollbar from "react-perfect-scrollbar";
import { getWalletsData } from './services/balance';

export default function Home() {
  const [data, setData] = useState([]);
  console.log(data)
  const getData = async () => {
    try {
      const res = await getWalletsData();
      const { data } = res
      const { data: newData } = data
      setData(newData ? newData : [])

    } catch (error) {
      console.log(error);

    }
  }
  useEffect(() => {
    getData()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <PerfectScrollbar>
          <Paper
            style={{
              width: "100%",
              // marginTop: theme.spacing.unit * 3,
              overflowX: "auto",
            }}
          >
            <Box>
              <h1 style={{ color: "#5a82d7", padding: '20px 5px' }}>Pre-Assessment Test Section#4 Part-3 Solution</h1>
              <Table>
                <TableHead sx={{ background: "#5a82d7" }}>
                  <TableRow>
                    <TableCell style={{ color: "#fff" }}>ID</TableCell>
                    <TableCell style={{ color: "#fff" }}>From_Address</TableCell>
                    <TableCell style={{ color: "#fff" }}>
                      Value
                    </TableCell>

                  </TableRow>
                </TableHead>

                <TableBody>
                  {data?.map((customer, index) => (
                    <TableRow
                      hover
                      key={index}
                    >
                      <TableCell>
                        <Box
                          sx={{
                            alignItems: "center",
                            display: "flex",
                          }}
                        >

                          <Typography color="textPrimary" variant="body1">
                            {index}
                          </Typography>
                        </Box>
                      </TableCell>
                      <TableCell>{customer?.from}</TableCell>


                      <TableCell>

                        {customer?.value}

                      </TableCell>


                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Box>
          </Paper>
        </PerfectScrollbar>


        <div className={styles.grid}>

        </div>
      </main>
    </>
  )
}
